CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN BYPASSRLS;

CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
$$ SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS
$$ SELECT COALESCE(NULLIF(current_setting('request.jwt.claim.role', true), ''), current_user) $$;

DO $fixture$
DECLARE
  object_name text;
BEGIN
  FOREACH object_name IN ARRAY ARRAY[
    'account', 'analyses', 'baseline_analytics', 'baseline_recompute_progress',
    'bertopic_clusters', 'channel_candidates', 'channel_discovery',
    'channel_performance_ratios', 'channels', 'chunks',
    'comments', 'daily_analytics', 'discovery_edges', 'discovery_method_metrics',
    'discovery_metrics', 'discovery_search_queries', 'documents',
    'ext_growth_cache', 'format_detection_feedback', 'google_pse_quota',
    'idea_heist_discoveries', 'old_patterns', 'patterns',
    'performance_envelopes', 'projects', 'quota_ledger', 'script_data',
    'session', 'skyscraper_analyses', 'thumbnail_battle_games',
    'thumbnail_battle_matchups', 'topic_categories', 'topic_hierarchy_mapping',
    'verification', 'video_patterns', 'video_performance_metrics',
    'thumbnail_versions', 'video_processing_jobs', 'videos', 'view_snapshots',
    'view_tracking_priority',
    'youtube_comments', 'youtube_quota_calls', 'youtube_quota_usage'
  ] LOOP
    EXECUTE format('CREATE TABLE public.%I (id text PRIMARY KEY, user_id uuid)', object_name);
  END LOOP;
END
$fixture$;

DO $legacy_fixture$
DECLARE
  object_name text;
BEGIN
  FOREACH object_name IN ARRAY ARRAY[
    'channel_import_status', 'channel_relationships', 'profiles',
    'thumbnail_battle_players', 'worker_control'
  ] LOOP
    EXECUTE format('CREATE TABLE public.%I (id text PRIMARY KEY)', object_name);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', object_name);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO PUBLIC USING (true) WITH CHECK (true)',
                   'Legacy unconditional client access', object_name);
  END LOOP;
END
$legacy_fixture$;

CREATE TABLE public.touch_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  ref text NOT NULL,
  source_url text,
  mode text NOT NULL,
  seen_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  result text
);

DO $fixture$
DECLARE
  object_name text;
BEGIN
  FOREACH object_name IN ARRAY ARRAY[
    'discovery_performance', 'format_distribution', 'llm_summary_status',
    'pending_channel_discoveries', 'quota_calls_summary', 'quota_daily_summary',
    'topic_distribution', 'topic_domain_summary', 'unprocessed_thumbnails',
    'video_classification_stats', 'videos_2024_unprocessed'
  ] LOOP
    EXECUTE format('CREATE VIEW public.%I AS SELECT 1::integer AS id', object_name);
  END LOOP;

  FOREACH object_name IN ARRAY ARRAY[
    'analytics_stats', 'channel_age_adjusted_performance', 'channel_network_centrality',
    'competitor_channel_summary', 'competitor_youtube_channels', 'database_channel_health',
    'database_data_quality', 'database_growth_stats', 'database_performance_stats',
    'heistable_videos', 'mv_makeorbreak_dashboard', 'packaging_performance',
    'thumbnail_battle_matchup_pool', 'topic_distribution_stats',
    'video_performance_trends'
  ] LOOP
    EXECUTE format('CREATE MATERIALIZED VIEW public.%I AS SELECT 1::integer AS id', object_name);
  END LOOP;
END
$fixture$;

CREATE FUNCTION public.refresh_dashboard_data() RETURNS integer
LANGUAGE sql SECURITY DEFINER AS $$ SELECT 1 $$;
CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO PUBLIC, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO PUBLIC, anon, authenticated, service_role;

CREATE POLICY "Allow public access to chunks" ON public.chunks FOR ALL USING (true);
CREATE POLICY "Allow public access to documents" ON public.documents FOR ALL USING (true);
CREATE POLICY "Allow public access to projects" ON public.projects FOR ALL USING (true);
CREATE POLICY "Allow public access to script_data" ON public.script_data FOR ALL USING (true);
CREATE POLICY "Allow public access to videos" ON public.videos FOR ALL USING (true);
