import dotenv from 'dotenv'; dotenv.config({path:'.env.local'});
import pg from 'pg';
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:2});
const r=await pool.query(`select distinct on (model_version) model_version, params from score_params where model_version in ('v5.0','v5.2') order by model_version, fitted_at desc`);
const m:any={}; for(const x of r.rows) m[x.model_version]=x.params;
const keys=Object.keys(m['v5.2'].mult).map(Number).sort((a,b)=>a-b);
console.log('bucket  v5.0    v5.2    ratio');
for(const k of keys) console.log(`${k.toFixed(4)}  ${(m['v5.0'].mult[k]??NaN).toFixed(3)}  ${m['v5.2'].mult[k].toFixed(3)}  ${(m['v5.2'].mult[k]/m['v5.0'].mult[k]).toFixed(4)}`);
console.log('longtail v5.0', JSON.stringify(m['v5.0'].longtail?.mult), 'v5.2', JSON.stringify(m['v5.2'].longtail?.mult));
await pool.end();
