begin;

create sequence if not exists public.pipeline_generation_seq;

create table if not exists public.observation_materialization_meta (
  singleton boolean primary key default true check (singleton),
  capture_started_at timestamptz not null default statement_timestamp()
);
insert into public.observation_materialization_meta(singleton) values(true) on conflict do nothing;

create table if not exists public.observation_change_log (
  change_id bigint generated by default as identity primary key,
  video_id text not null,
  source text not null check (source in ('snapshot','sample','rss')),
  operation text not null check (operation in ('upsert','delete')),
  at timestamptz not null,
  views bigint,
  time_basis text,
  received_at timestamptz,
  model_eligible boolean not null default true,
  conflicted boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists observation_change_log_video_change_idx
  on public.observation_change_log(video_id, change_id);

create table if not exists public.obs_cache_dirty (
  video_id text primary key,
  generation bigint not null,
  requires_bootstrap boolean not null default false,
  marked_at timestamptz not null default now(),
  not_before timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text
);
create index if not exists obs_cache_dirty_due_idx
  on public.obs_cache_dirty(not_before, marked_at, video_id);

create table if not exists public.score_dirty (
  video_id text primary key,
  generation bigint not null default nextval('public.pipeline_generation_seq'),
  reason text not null default 'observation',
  marked_at timestamptz not null default now(),
  not_before timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text
);
create index if not exists score_dirty_due_idx
  on public.score_dirty(not_before, marked_at, video_id);

create table if not exists public.series_dirty (
  video_id text primary key,
  marked_at timestamptz not null default now(),
  attempts integer not null default 0
);
alter table public.series_dirty add column if not exists generation bigint not null default 0;

create table if not exists public.video_obs_cache (
  video_id text primary key,
  built_at timestamptz not null default now(),
  n integer not null,
  obs bytea not null
);
alter table public.video_obs_cache add column if not exists format smallint not null default 1;
alter table public.video_obs_cache add column if not exists last_change_id bigint not null default 0;
alter table public.video_obs_cache alter column obs set storage external;

create table if not exists public.video_day30_truth (
  video_id text primary key,
  snapshot_day integer not null,
  snapshot_date date not null,
  views bigint not null
);

alter table public.observation_change_log enable row level security;
alter table public.obs_cache_dirty enable row level security;
alter table public.score_dirty enable row level security;
alter table public.observation_materialization_meta enable row level security;
alter table public.series_dirty enable row level security;
alter table public.video_obs_cache enable row level security;
alter table public.video_day30_truth enable row level security;
revoke all on table public.observation_change_log, public.obs_cache_dirty, public.score_dirty,
  public.observation_materialization_meta, public.series_dirty, public.video_obs_cache,
  public.video_day30_truth
  from anon, authenticated;
revoke all on sequence public.pipeline_generation_seq,
  public.observation_change_log_change_id_seq from anon, authenticated;

create or replace function public.enqueue_observation_changes(p_rows jsonb)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  affected integer;
begin
  if p_rows is null or jsonb_array_length(p_rows) = 0 then return; end if;
  with logged as (
    insert into public.observation_change_log
      (video_id, source, operation, at, views, time_basis, received_at, model_eligible, conflicted)
    select x.video_id, x.source, x.operation, x.at, x.views, x.time_basis, x.received_at,
           coalesce(x.model_eligible, true), coalesce(x.conflicted, false)
      from jsonb_array_elements(p_rows) with ordinality as item(payload, position)
      cross join lateral jsonb_to_record(item.payload) as x(
        video_id text, source text, operation text, at timestamptz, views bigint,
        time_basis text, received_at timestamptz, model_eligible boolean, conflicted boolean)
      join public.videos v on v.id=x.video_id
     where x.video_id is not null and x.video_id <> '' and x.at is not null
     order by item.position
    returning video_id, change_id
  ), per_video as materialized (
    select video_id, max(change_id) as generation from logged group by video_id
  ), obs_queue as (
    insert into public.obs_cache_dirty(video_id, generation, requires_bootstrap, marked_at, not_before)
    select p.video_id, p.generation,
           not exists (select 1 from public.video_obs_cache c where c.video_id=p.video_id and c.format=2)
           and not coalesce(v.import_date >= m.capture_started_at, false),
           now(), now()
      from per_video p
      join public.videos v on v.id=p.video_id
      join public.observation_materialization_meta m on m.singleton
    on conflict (video_id) do update set
      generation = greatest(public.obs_cache_dirty.generation, excluded.generation),
      requires_bootstrap = public.obs_cache_dirty.requires_bootstrap or excluded.requires_bootstrap,
      marked_at = excluded.marked_at,
      not_before = least(public.obs_cache_dirty.not_before, excluded.not_before)
    returning video_id
  ), score_queue as (
    insert into public.score_dirty(video_id, generation, reason, marked_at, not_before)
    select p.video_id, nextval('public.pipeline_generation_seq'), 'observation', now(),
           case when sc.scored_at is null then now()
                else sc.scored_at + case
                  when now() - v.published_at < interval '1 day' then interval '5 minutes'
                  when now() - v.published_at < interval '7 days' then interval '1 hour'
                  when now() - v.published_at < interval '30 days' then interval '1 day'
                  when now() - v.published_at < interval '60 days' then interval '3 days'
                  else interval '7 days'
                end
           end
      from per_video p
      join public.videos v on v.id=p.video_id
      left join public.video_scores sc on sc.video_id=p.video_id
     where v.published_at is not null
       and coalesce(v.privacy_status,'public') = 'public'
       and coalesce(v.is_short,false) = false
       and coalesce(v.duration,'') <> 'P0D'
       and not (v.shorts_checked_at is null
                and v.duration ~ '^PT[0-9HMS]+$'
                and extract(epoch from v.duration::interval) <= 180)
    on conflict (video_id) do update set
      generation = excluded.generation,
      reason = case when public.score_dirty.reason = 'model-rollout'
                    then public.score_dirty.reason else excluded.reason end,
      marked_at = excluded.marked_at,
      not_before = least(public.score_dirty.not_before, excluded.not_before)
    returning video_id
  ), series_queue as (
    insert into public.series_dirty(video_id, marked_at, generation)
    select p.video_id, now(), nextval('public.pipeline_generation_seq') from per_video p
      join public.videos v on v.id=p.video_id
    on conflict (video_id) do update set
      marked_at = excluded.marked_at, generation = excluded.generation
    returning video_id
  )
  select count(*) into affected from per_video;
end;
$$;

-- RSS discovery can observe a catalog id before the corresponding videos row is imported. Such
-- observations are deliberately not retained forever in the delta log. If the video is imported
-- later, bootstrap its already-present raw history once instead of pretending it started empty.
create or replace function public.queue_new_video_bootstraps()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  insert into public.obs_cache_dirty(video_id, generation, requires_bootstrap, marked_at, not_before)
  select n.id, 0, true, now(), now()
    from new_videos n
   where not exists (
           select 1 from public.video_obs_cache c where c.video_id=n.id and c.format=2)
     and (exists (select 1 from public.view_snapshots s where s.video_id=n.id)
       or exists (select 1 from public.view_samples s where s.video_id=n.id)
       or exists (select 1 from public.rss_samples s where s.video_id=n.id))
  on conflict (video_id) do update set
    requires_bootstrap=true, marked_at=excluded.marked_at,
    not_before=least(public.obs_cache_dirty.not_before,excluded.not_before);
  return null;
end $$;

-- The scorer used to re-read view_snapshots for every prior's exact day-30 anchor after its
-- compact observation-cache hit. Keep that small fact event-maintained instead: the scheduled
-- scorer receives it through the same cache query and never opens a raw history table.
create or replace function public.refresh_day30_truth(p_video_ids text[])
returns void language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if p_video_ids is null or cardinality(p_video_ids) = 0 then return; end if;
  delete from public.video_day30_truth where video_id=any(p_video_ids);
  insert into public.video_day30_truth(video_id,snapshot_day,snapshot_date,views)
  select distinct on (s.video_id)
         s.video_id, s.days_since_published, s.snapshot_date, s.view_count
    from public.view_snapshots s
   where s.video_id=any(p_video_ids)
     and s.days_since_published between 27 and 33
     and s.view_count > 0
   order by s.video_id, abs(s.days_since_published - 30), s.snapshot_date desc;
end $$;

create or replace function public.queue_snapshot_upserts()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','snapshot','operation','upsert',
    'at',snapshot_date::timestamptz + interval '12 hours','views',view_count)) from new_rows));
  perform public.refresh_day30_truth(array(select distinct video_id from new_rows));
  return null;
end $$;
create or replace function public.queue_snapshot_deletes()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','snapshot','operation','delete',
    'at',snapshot_date::timestamptz + interval '12 hours')) from old_rows));
  perform public.refresh_day30_truth(array(select distinct video_id from old_rows));
  return null;
end $$;
create or replace function public.queue_snapshot_updates()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(payload order by phase) from (
    select jsonb_build_object(
      'video_id',video_id,'source','snapshot','operation','delete',
      'at',snapshot_date::timestamptz + interval '12 hours') as payload, 0 as phase from old_rows
    union all
    select jsonb_build_object(
      'video_id',video_id,'source','snapshot','operation','upsert',
      'at',snapshot_date::timestamptz + interval '12 hours','views',view_count), 1 from new_rows
  ) changes));
  perform public.refresh_day30_truth(array(
    select video_id from old_rows union select video_id from new_rows
  ));
  return null;
end $$;

create or replace function public.queue_sample_upserts()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','sample','operation','upsert',
    'at',sampled_at,'views',view_count)) from new_rows));
  return null;
end $$;
create or replace function public.queue_sample_deletes()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','sample','operation','delete','at',sampled_at)) from old_rows));
  return null;
end $$;
create or replace function public.queue_sample_updates()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(payload order by phase) from (
    select jsonb_build_object(
      'video_id',video_id,'source','sample','operation','delete','at',sampled_at) as payload, 0 as phase from old_rows
    union all
    select jsonb_build_object(
      'video_id',video_id,'source','sample','operation','upsert',
      'at',sampled_at,'views',view_count), 1 from new_rows
  ) changes));
  return null;
end $$;

create or replace function public.queue_rss_upserts()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','rss','operation','upsert','at',at,'views',views,
    'time_basis',time_basis,'received_at',received_at,'model_eligible',model_eligible,
    'conflicted',conflicted)) from new_rows));
  return null;
end $$;
create or replace function public.queue_rss_deletes()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','rss','operation','delete','at',at)) from old_rows));
  return null;
end $$;
create or replace function public.queue_rss_updates()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(payload order by phase) from (
    select jsonb_build_object(
      'video_id',video_id,'source','rss','operation','delete','at',at) as payload, 0 as phase from old_rows
    union all
    select jsonb_build_object(
      'video_id',video_id,'source','rss','operation','upsert','at',at,'views',views,
      'time_basis',time_basis,'received_at',received_at,'model_eligible',model_eligible,
      'conflicted',conflicted), 1 from new_rows
  ) changes));
  return null;
end $$;

revoke execute on function public.enqueue_observation_changes(jsonb) from public, anon, authenticated;
revoke execute on function public.refresh_day30_truth(text[]) from public, anon, authenticated;
revoke execute on function public.queue_new_video_bootstraps(),
  public.queue_snapshot_upserts(), public.queue_snapshot_deletes(),
  public.queue_snapshot_updates(), public.queue_sample_upserts(), public.queue_sample_deletes(),
  public.queue_sample_updates(), public.queue_rss_upserts(), public.queue_rss_deletes(),
  public.queue_rss_updates() from public, anon, authenticated;

drop trigger if exists queue_videos_insert_bootstrap on public.videos;
create trigger queue_videos_insert_bootstrap after insert on public.videos
  referencing new table as new_videos for each statement execute function public.queue_new_video_bootstraps();

drop trigger if exists queue_view_snapshots_insert on public.view_snapshots;
create trigger queue_view_snapshots_insert after insert on public.view_snapshots
  referencing new table as new_rows for each statement execute function public.queue_snapshot_upserts();
drop trigger if exists queue_view_snapshots_update on public.view_snapshots;
create trigger queue_view_snapshots_update after update on public.view_snapshots
  referencing old table as old_rows new table as new_rows
  for each statement execute function public.queue_snapshot_updates();
drop trigger if exists queue_view_snapshots_delete on public.view_snapshots;
create trigger queue_view_snapshots_delete after delete on public.view_snapshots
  referencing old table as old_rows for each statement execute function public.queue_snapshot_deletes();

drop trigger if exists queue_view_samples_insert on public.view_samples;
create trigger queue_view_samples_insert after insert on public.view_samples
  referencing new table as new_rows for each statement execute function public.queue_sample_upserts();
drop trigger if exists queue_view_samples_update on public.view_samples;
create trigger queue_view_samples_update after update on public.view_samples
  referencing old table as old_rows new table as new_rows
  for each statement execute function public.queue_sample_updates();
drop trigger if exists queue_view_samples_delete on public.view_samples;
create trigger queue_view_samples_delete after delete on public.view_samples
  referencing old table as old_rows for each statement execute function public.queue_sample_deletes();

drop trigger if exists queue_rss_samples_insert on public.rss_samples;
create trigger queue_rss_samples_insert after insert on public.rss_samples
  referencing new table as new_rows for each statement execute function public.queue_rss_upserts();
drop trigger if exists queue_rss_samples_update on public.rss_samples;
create trigger queue_rss_samples_update after update on public.rss_samples
  referencing old table as old_rows new table as new_rows
  for each statement execute function public.queue_rss_updates();
drop trigger if exists queue_rss_samples_delete on public.rss_samples;
create trigger queue_rss_samples_delete after delete on public.rss_samples
  referencing old table as old_rows for each statement execute function public.queue_rss_deletes();

-- Existing format-1 rows remain readable to interactive paths but require one exact v2 bootstrap
-- before the batch scorer can trust them.
insert into public.obs_cache_dirty(video_id, generation, requires_bootstrap)
select video_id, 0, true from public.video_obs_cache where format <> 2
on conflict (video_id) do update set requires_bootstrap=true, marked_at=now();

insert into public.video_day30_truth(video_id,snapshot_day,snapshot_date,views)
select distinct on (s.video_id)
       s.video_id, s.days_since_published, s.snapshot_date, s.view_count
  from public.view_snapshots s
 where s.days_since_published between 27 and 33 and s.view_count > 0
 order by s.video_id, abs(s.days_since_published - 30), s.snapshot_date desc
on conflict (video_id) do update set
  snapshot_day=excluded.snapshot_day,
  snapshot_date=excluded.snapshot_date,
  views=excluded.views;

commit;
