begin;

create sequence if not exists public.pipeline_generation_seq;

create table if not exists public.observation_materialization_meta (
  singleton boolean primary key default true check (singleton),
  capture_started_at timestamptz not null default statement_timestamp()
);
insert into public.observation_materialization_meta(singleton) values(true) on conflict do nothing;

create table if not exists public.observation_change_log (
  change_id bigint generated by default as identity primary key,
  video_id text not null,
  source text not null check (source in ('snapshot','sample','rss')),
  operation text not null check (operation in ('upsert','delete')),
  at timestamptz not null,
  views bigint,
  time_basis text,
  received_at timestamptz,
  model_eligible boolean not null default true,
  conflicted boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists observation_change_log_video_change_idx
  on public.observation_change_log(video_id, change_id);

create table if not exists public.obs_cache_dirty (
  video_id text primary key,
  generation bigint not null,
  requires_bootstrap boolean not null default false,
  marked_at timestamptz not null default now(),
  not_before timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text
);
create index if not exists obs_cache_dirty_due_idx
  on public.obs_cache_dirty(not_before, marked_at, video_id);

create table if not exists public.score_dirty (
  video_id text primary key,
  generation bigint not null default nextval('public.pipeline_generation_seq'),
  reason text not null default 'observation',
  marked_at timestamptz not null default now(),
  not_before timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text
);
create index if not exists score_dirty_due_idx
  on public.score_dirty(not_before, marked_at, video_id);

create table if not exists public.series_dirty (
  video_id text primary key,
  marked_at timestamptz not null default now(),
  attempts integer not null default 0
);
alter table public.series_dirty add column if not exists generation bigint not null default 0;

create table if not exists public.video_obs_cache (
  video_id text primary key,
  built_at timestamptz not null default now(),
  n integer not null,
  obs bytea not null
);
alter table public.video_obs_cache add column if not exists format smallint not null default 1;
alter table public.video_obs_cache add column if not exists last_change_id bigint not null default 0;
alter table public.video_obs_cache alter column obs set storage external;

alter table public.observation_change_log enable row level security;
alter table public.obs_cache_dirty enable row level security;
alter table public.score_dirty enable row level security;
alter table public.observation_materialization_meta enable row level security;
revoke all on table public.observation_change_log, public.obs_cache_dirty, public.score_dirty,
  public.observation_materialization_meta from anon, authenticated;
revoke all on sequence public.pipeline_generation_seq from anon, authenticated;

create or replace function public.enqueue_observation_changes(p_rows jsonb)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  affected integer;
begin
  if p_rows is null or jsonb_array_length(p_rows) = 0 then return; end if;
  with logged as (
    insert into public.observation_change_log
      (video_id, source, operation, at, views, time_basis, received_at, model_eligible, conflicted)
    select video_id, source, operation, at, views, time_basis, received_at,
           coalesce(model_eligible, true), coalesce(conflicted, false)
      from jsonb_to_recordset(p_rows) as x(
        video_id text, source text, operation text, at timestamptz, views bigint,
        time_basis text, received_at timestamptz, model_eligible boolean, conflicted boolean)
     where video_id is not null and video_id <> '' and at is not null
    returning video_id, change_id
  ), per_video as materialized (
    select video_id, max(change_id) as generation from logged group by video_id
  ), obs_queue as (
    insert into public.obs_cache_dirty(video_id, generation, requires_bootstrap, marked_at, not_before)
    select p.video_id, p.generation,
           not exists (select 1 from public.video_obs_cache c where c.video_id=p.video_id and c.format=2),
           now(), now()
      from per_video p
    on conflict (video_id) do update set
      generation = greatest(public.obs_cache_dirty.generation, excluded.generation),
      requires_bootstrap = public.obs_cache_dirty.requires_bootstrap or excluded.requires_bootstrap,
      marked_at = excluded.marked_at,
      not_before = least(public.obs_cache_dirty.not_before, excluded.not_before)
    returning video_id
  ), score_queue as (
    insert into public.score_dirty(video_id, generation, reason, marked_at, not_before)
    select p.video_id, nextval('public.pipeline_generation_seq'), 'observation', now(), now()
      from per_video p
    on conflict (video_id) do update set
      generation = excluded.generation, reason = excluded.reason,
      marked_at = excluded.marked_at,
      not_before = least(public.score_dirty.not_before, excluded.not_before)
    returning video_id
  ), series_queue as (
    insert into public.series_dirty(video_id, marked_at, generation)
    select p.video_id, now(), nextval('public.pipeline_generation_seq') from per_video p
    on conflict (video_id) do update set
      marked_at = excluded.marked_at, generation = excluded.generation
    returning video_id
  )
  select count(*) into affected from per_video;
end;
$$;

create or replace function public.queue_snapshot_upserts()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','snapshot','operation','upsert',
    'at',snapshot_date::timestamptz + interval '12 hours','views',view_count)) from new_rows));
  return null;
end $$;
create or replace function public.queue_snapshot_deletes()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','snapshot','operation','delete',
    'at',snapshot_date::timestamptz + interval '12 hours')) from old_rows));
  return null;
end $$;

create or replace function public.queue_sample_upserts()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','sample','operation','upsert',
    'at',sampled_at,'views',view_count)) from new_rows));
  return null;
end $$;
create or replace function public.queue_sample_deletes()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','sample','operation','delete','at',sampled_at)) from old_rows));
  return null;
end $$;

create or replace function public.queue_rss_upserts()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','rss','operation','upsert','at',at,'views',views,
    'time_basis',time_basis,'received_at',received_at,'model_eligible',model_eligible,
    'conflicted',conflicted)) from new_rows));
  return null;
end $$;
create or replace function public.queue_rss_deletes()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  perform public.enqueue_observation_changes((select jsonb_agg(jsonb_build_object(
    'video_id',video_id,'source','rss','operation','delete','at',at)) from old_rows));
  return null;
end $$;

drop trigger if exists queue_view_snapshots_insert on public.view_snapshots;
create trigger queue_view_snapshots_insert after insert on public.view_snapshots
  referencing new table as new_rows for each statement execute function public.queue_snapshot_upserts();
drop trigger if exists queue_view_snapshots_update on public.view_snapshots;
create trigger queue_view_snapshots_update after update on public.view_snapshots
  referencing new table as new_rows for each statement execute function public.queue_snapshot_upserts();
drop trigger if exists queue_view_snapshots_delete on public.view_snapshots;
create trigger queue_view_snapshots_delete after delete on public.view_snapshots
  referencing old table as old_rows for each statement execute function public.queue_snapshot_deletes();

drop trigger if exists queue_view_samples_insert on public.view_samples;
create trigger queue_view_samples_insert after insert on public.view_samples
  referencing new table as new_rows for each statement execute function public.queue_sample_upserts();
drop trigger if exists queue_view_samples_update on public.view_samples;
create trigger queue_view_samples_update after update on public.view_samples
  referencing new table as new_rows for each statement execute function public.queue_sample_upserts();
drop trigger if exists queue_view_samples_delete on public.view_samples;
create trigger queue_view_samples_delete after delete on public.view_samples
  referencing old table as old_rows for each statement execute function public.queue_sample_deletes();

drop trigger if exists queue_rss_samples_insert on public.rss_samples;
create trigger queue_rss_samples_insert after insert on public.rss_samples
  referencing new table as new_rows for each statement execute function public.queue_rss_upserts();
drop trigger if exists queue_rss_samples_update on public.rss_samples;
create trigger queue_rss_samples_update after update on public.rss_samples
  referencing new table as new_rows for each statement execute function public.queue_rss_upserts();
drop trigger if exists queue_rss_samples_delete on public.rss_samples;
create trigger queue_rss_samples_delete after delete on public.rss_samples
  referencing old table as old_rows for each statement execute function public.queue_rss_deletes();

-- Existing format-1 rows remain readable to interactive paths but require one exact v2 bootstrap
-- before the batch scorer can trust them.
insert into public.obs_cache_dirty(video_id, generation, requires_bootstrap)
select video_id, 0, true from public.video_obs_cache where format <> 2
on conflict (video_id) do update set requires_bootstrap=true, marked_at=now();

commit;
