begin;
drop trigger if exists queue_view_snapshots_insert on public.view_snapshots;
drop trigger if exists queue_view_snapshots_update on public.view_snapshots;
drop trigger if exists queue_view_snapshots_delete on public.view_snapshots;
drop trigger if exists queue_view_samples_insert on public.view_samples;
drop trigger if exists queue_view_samples_update on public.view_samples;
drop trigger if exists queue_view_samples_delete on public.view_samples;
drop trigger if exists queue_rss_samples_insert on public.rss_samples;
drop trigger if exists queue_rss_samples_update on public.rss_samples;
drop trigger if exists queue_rss_samples_delete on public.rss_samples;
drop function if exists public.queue_snapshot_upserts();
drop function if exists public.queue_snapshot_deletes();
drop function if exists public.queue_sample_upserts();
drop function if exists public.queue_sample_deletes();
drop function if exists public.queue_rss_upserts();
drop function if exists public.queue_rss_deletes();
drop function if exists public.enqueue_observation_changes(jsonb);
drop table if exists public.score_dirty;
drop table if exists public.obs_cache_dirty;
drop table if exists public.observation_change_log;
alter table if exists public.video_obs_cache drop column if exists last_change_id;
alter table if exists public.video_obs_cache drop column if exists format;
alter table if exists public.series_dirty drop column if exists generation;
drop sequence if exists public.pipeline_generation_seq;
commit;
