begin;
drop trigger if exists queue_videos_insert_bootstrap on public.videos;
drop trigger if exists queue_view_snapshots_insert on public.view_snapshots;
drop trigger if exists queue_view_snapshots_update on public.view_snapshots;
drop trigger if exists queue_view_snapshots_delete on public.view_snapshots;
drop trigger if exists queue_view_samples_insert on public.view_samples;
drop trigger if exists queue_view_samples_update on public.view_samples;
drop trigger if exists queue_view_samples_delete on public.view_samples;
drop trigger if exists queue_rss_samples_insert on public.rss_samples;
drop trigger if exists queue_rss_samples_update on public.rss_samples;
drop trigger if exists queue_rss_samples_delete on public.rss_samples;
drop function if exists public.queue_snapshot_upserts();
drop function if exists public.queue_snapshot_deletes();
drop function if exists public.queue_snapshot_updates();
drop function if exists public.queue_sample_upserts();
drop function if exists public.queue_sample_deletes();
drop function if exists public.queue_sample_updates();
drop function if exists public.queue_rss_upserts();
drop function if exists public.queue_rss_deletes();
drop function if exists public.queue_rss_updates();
drop function if exists public.queue_new_video_bootstraps();
drop function if exists public.refresh_day30_truth(text[]);
drop function if exists public.enqueue_observation_changes(jsonb);
drop table if exists public.video_day30_truth;
drop table if exists public.score_dirty;
drop table if exists public.obs_cache_dirty;
drop table if exists public.observation_change_log;
drop table if exists public.observation_materialization_meta;
alter table if exists public.video_obs_cache drop column if exists last_change_id;
alter table if exists public.video_obs_cache drop column if exists format;
alter table if exists public.series_dirty drop column if exists generation;
alter table if exists public.video_obs_cache disable row level security;
alter table if exists public.series_dirty disable row level security;
drop sequence if exists public.pipeline_generation_seq;
commit;
