-- video_score_history → one partition per UTC day (2026-09-26). AWAITING APPROVAL; not applied.
--
-- Why: retention by DELETE never returns disk; a full rescoring burst left the heap at 1,280 MB with
-- 92.7 % free until a one-time pg_repack. With daily partitions, retention is DROP TABLE of an
-- archived day (scripts/thin-readings.ts), so a burst leaves on its own after 14 days.
--
-- Run on the SESSION pooler (single transaction, ~200 K rows / ~90 MB copied; writers blocked for
-- the copy; new readers may queue up to 5 s at the rename; measured on a clone in lib/readings/history-partitions.integration.test.ts):
--   psql "$DATABASE_SESSION_URL" -v ON_ERROR_STOP=1 -f sql/2026-09-26-partition-video-score-history.sql
-- Then, after a minute, copy into the new table any straggler rows a writer that was queued behind
-- the lock put into the renamed old one:
--   insert into video_score_history select * from video_score_history_unpartitioned u
--    where not exists (select 1 from video_score_history n where n.id = u.id);
-- (not `id > max(id)`: the sequence is shared, so a straggler can sit below a newer row.)
--   drop table video_score_history_unpartitioned;
-- Rollback (before the drop): sql/rollback/2026-09-26-partition-video-score-history.sql

-- Generated by lib/readings/history-partitions.ts partitionMigrationSql(). Do not edit by hand.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '300s';
-- Blocks writers (the scorer) for the copy; readers carry on. Fails in 5 s rather than queueing.
lock table public.video_score_history in share row exclusive mode;

create table public.video_score_history_next (like public.video_score_history including defaults including constraints including comments)
  partition by range (scored_at);
alter table public.video_score_history_next add primary key (id, scored_at);
create index on public.video_score_history_next (model_version, scored_at);
create table public.video_score_history_next_default partition of public.video_score_history_next default;

do $$
declare d date; last date := (now() at time zone 'utc')::date + 7;
begin
  select coalesce(min((scored_at at time zone 'utc')::date), (now() at time zone 'utc')::date)
    into d from public.video_score_history;
  while d <= last loop
    execute format('create table %I.%I partition of %I.%I for values from (%L) to (%L)',
      'public', 'video_score_history_p' || to_char(d, 'YYYYMMDD'), 'public', 'video_score_history_next',
      to_char(d, 'YYYY-MM-DD') || ' 00:00:00+00', to_char(d + 1, 'YYYY-MM-DD') || ' 00:00:00+00');
    d := d + 1;
  end loop;
end $$;

insert into public.video_score_history_next select * from public.video_score_history;

do $$
begin
  if (select count(*) from public.video_score_history_next) <> (select count(*) from public.video_score_history) then
    raise exception 'row count mismatch; nothing changed';
  end if;
  if exists (select 1 from public.video_score_history_next_default) then
    raise exception 'rows landed in the default partition; nothing changed';
  end if;
end $$;

alter sequence public.video_score_history_id_seq owned by public.video_score_history_next.id;
alter table public.video_score_history rename to video_score_history_unpartitioned;
alter table public.video_score_history_next rename to video_score_history;
alter table public.video_score_history_next_default rename to video_score_history_default;
grant all on public.video_score_history to channelsmith_app;

-- The view follows the OLD table's oid through the rename; point it at the new one.
create or replace view public.video_scores_by_version as
  select distinct on (h.video_id, h.model_version) h.id, h.video_id, h.channel_id, h.model_version,
         h.scored_at, h.age_days, h.views, h.score, h.same_age_ratio, h.typical_at_age, h.n_typical,
         h.typical_measured_share, h.projection, h.projection_horizon, h.est30, h.baseline,
         h.n_baseline, h.confidence, h.extra
    from public.video_score_history h
   order by h.video_id, h.model_version, h.scored_at desc;
commit;
