-- NOT APPLIED. Needs Brandon's go — it changes write behaviour on the hottest table.
--
-- `trigger_set_video_is_short` fires BEFORE INSERT OR UPDATE OF duration, title, description on
-- `videos` and sets is_short := is_youtube_short(duration, title, description), which is TRUE for
-- any duration <= 180 s or any title/description containing #shorts. That is the pre-2024 Shorts
-- rule as a hard database override: it discards the verdict every ingest path just obtained from
-- YouTube's own /shorts/<id> routing (lib/ingest/classify.ts -> lib/thumbs/shorts.ts), so a
-- 61-180 s long-form video is inserted as a Short while the application writes
-- shorts_checked_at = now() next to it. lib/scoring/longform.ts trusts a stamped row, so the
-- video is excluded from every baseline and never re-checked.
--
-- Measured 2026-09-04 (ET): of the 2,000 most recently stamped 61-180 s is_short rows, 1,369
-- (68 %) are actually long-form (303 -> /watch); among rows inserted within the last few hours it
-- is ~100 %. The trigger also fires on UPDATE OF title/description, so a title-change stamp can
-- silently flip an already-verified long-form video back to Short.
--
-- The rule now lives in exactly one place: lib/ingest/classify.ts + lib/thumbs/shorts.ts.
drop trigger if exists trigger_set_video_is_short on public.videos;

-- Keep the function itself (other reporting SQL may still reference it) but nothing should call it
-- as a source of truth. Uncomment to remove it entirely once nothing does:
-- drop function if exists public.set_video_is_short();
