-- Fast SQL update for BERTopic hierarchy v3
-- This updates all videos in a single pass using a temporary mapping table

-- Create temporary mapping table
CREATE TEMP TABLE topic_hierarchy_mapping (
  cluster_id INTEGER PRIMARY KEY,
  new_domain TEXT,
  new_niche TEXT,
  new_micro TEXT
);

-- Insert all mappings
INSERT INTO topic_hierarchy_mapping VALUES
(0, 'DIY & Crafts', 'Woodworking', 'Woodworking Projects & Tool Reviews'),
(1, 'Business', 'Finance & Trading', 'AI Business & Stock Trading'),
(2, 'Lifestyle', 'Home & Organization', 'Home Cleaning & Organization Routines'),
(3, 'Health & Fitness', 'Workouts', 'Running & Fitness Training'),
(4, 'Lifestyle', 'Alternative Living', 'Tiny Living & Alternative Housing'),
(5, 'Technology', 'Electric Vehicles', 'Tesla & Electric Vehicle Reviews'),
(6, 'Music', 'Instruments', 'Guitar Tutorials & Music Gear'),
(7, 'Travel', 'Theme Parks', 'Disney Parks & Travel Vlogs'),
(8, 'Technology', 'Other', 'Live Streaming & 3D Content'),
(9, 'Business', 'Digital Marketing', 'Instagram Marketing & E-commerce'),
(10, 'Technology', 'Audio Technology', 'Audio Equipment & Music Production'),
(11, 'Finance', 'Investing', 'Stock Market & Real Estate Investing'),
(12, 'Technology', 'Photography & Video', 'Camera Gear & Photography Reviews'),
(13, 'Education', 'Language Learning', 'Spanish Language Learning'),
(14, 'Business', 'Digital Marketing', 'YouTube Channel Growth Strategies'),
(15, 'DIY & Crafts', 'Woodworking', 'Creative Woodworking Ideas'),
(16, 'Business', 'Entrepreneurship', 'Business Scaling & Entrepreneurship'),
(17, 'Technology', 'AI & Innovation', 'AI Tools & Technology News'),
(18, 'Gaming', 'Gameplay', 'Live Stream Gaming & Tech'),
(19, 'Food & Cooking', 'Recipes', 'Food & Cooking Tutorials'),
(20, 'Gaming', 'Gameplay', 'Minecraft Gameplay & Tutorials'),
(21, 'Education', 'Academic Subjects', 'Art History & Cultural Education'),
(22, 'Technology', '3D Printing', '3D Printing Projects & Tutorials'),
(23, 'Food & Cooking', 'Recipes', 'Meal Prep & Healthy Eating'),
(24, 'Hobbies', 'LEGO', 'LEGO Building & Set Reviews'),
(25, 'Arts & Media', 'Photo Editing', 'Photography Editing & Techniques'),
(26, 'Travel', 'Adventure Travel', 'Adventure Travel & Exploration'),
(27, 'Lifestyle', 'Other', 'Personal Development & Life Coaching'),
(28, 'Technology', 'Gaming Tech', 'Gaming Hardware & PC Building'),
(29, 'Music', 'Music Production', 'Professional Music Production'),
(30, 'Education', 'Academic Subjects', 'Study Tips & Academic Success'),
(31, 'Lifestyle', 'Other', 'Christian Faith & Bible Study'),
(32, 'Business', 'Other', 'Motivational Speaking & Leadership'),
(33, 'Technology', 'Electric Vehicles', 'Tech Product Unboxings'),
(34, 'Business', 'Digital Marketing', 'Content Creation Tools & Tips'),
(35, 'DIY & Crafts', 'Digital Fabrication', 'Laser Cutting & CNC Projects'),
(36, 'Lifestyle', 'Home & Organization', 'Minimalist Lifestyle & Decluttering'),
(37, 'Travel', 'Destination Guides', 'Travel Planning & Destination Guides'),
(38, 'Education', 'Educational Content', 'Educational Documentary Content'),
(39, 'Home & Garden', 'Renovation', 'Home Renovation & Improvement'),
(40, 'Education', 'Academic Subjects', 'Science Experiments & STEM Education'),
(41, 'Technology', 'Photography & Video', 'Drone Flying & Aerial Photography'),
(42, 'Business', 'E-commerce', 'Online Business & Passive Income'),
(43, 'Technology', 'Tech Industry', 'Tech Industry News & Analysis'),
(44, 'Lifestyle', 'Family Life', 'Family Vlogs & Parenting'),
(45, 'Outdoors', 'Camping', 'Outdoor Adventure & Camping'),
(46, 'Education', 'Academic Subjects', 'History Documentaries & Education'),
(47, 'Education', 'Other', 'Historical Analysis & Storytelling'),
(48, 'Entertainment', 'True Crime', 'Mystery & True Crime Content'),
(49, 'Travel', 'Adventure Travel', 'Travel Adventures & Culture'),
(50, 'Lifestyle', 'Other', 'Budget Living & Frugal Tips'),
(51, 'DIY & Crafts', 'Woodworking', 'Furniture Making & Wood Design'),
(52, 'Home & Garden', 'Organization', 'Home Storage & Organization Solutions'),
(53, 'Business', 'Creative Business', 'Professional Photography Business'),
(54, 'Lifestyle', 'Fashion & Beauty', 'Daily Vlogs & Lifestyle Content'),
(55, 'Music', 'Performance', 'Music Performance & Covers'),
(56, 'Lifestyle', 'Wellness', 'Personal Growth & Mindfulness'),
(57, 'DIY & Crafts', 'Metalworking', 'Metalworking & Knife Making'),
(58, 'Sports', 'Extreme Sports', 'Adventure Sports & Extreme Activities'),
(59, 'Technology', 'Programming', 'Programming & Coding Tutorials'),
(60, 'Entertainment', 'Pop Culture', 'Entertainment News & Pop Culture'),
(61, 'Food & Cooking', 'Food Reviews', 'Restaurant Reviews & Food Tours'),
(62, 'Lifestyle', 'Daily Vlogs', 'Morning Routines & Productivity'),
(63, 'Music', 'Instruments', 'Music Theory & Instrument Lessons'),
(64, 'DIY & Crafts', 'Woodworking', 'Cabinet Making & Fine Woodworking'),
(65, 'News & Politics', 'Current Events', 'World News & Current Events'),
(66, 'Outdoors', 'Gear Reviews', 'Camping Gear Reviews & Tips'),
(67, 'Lifestyle', 'Other', 'Inspirational Content & Life Stories'),
(68, 'Business', 'E-commerce', 'E-commerce & Amazon FBA'),
(69, 'Arts & Media', 'Painting', 'Painting Techniques & Art Tutorials'),
(70, 'Home & Garden', 'Home Repair', 'Home Repairs & Maintenance'),
(71, 'Finance', 'Real Estate', 'Real Estate Investment Strategies'),
(72, 'Home & Garden', 'Bathrooms', 'Bathroom Renovations & Plumbing'),
(73, 'Travel', 'Other', 'RV Life & Mobile Living'),
(74, 'Education', 'Educational Content', 'Educational Explainer Videos'),
(75, 'Entertainment', 'Star Wars', 'Star Wars Fan Content & Reviews'),
(76, 'Outdoors', 'Survival', 'Outdoor Survival & Bushcraft'),
(77, 'Music', 'Music Gear', 'Music Gear Reviews & Demos'),
(78, 'Home & Garden', 'Kitchens', 'Kitchen Design & Renovation'),
(79, 'Music', 'Music Production', 'Professional Audio Engineering'),
(80, 'Arts & Media', 'Art Education', 'Art Techniques & Creative Process'),
(81, 'Home & Garden', 'Small Spaces', 'Small Space Design Solutions'),
(82, 'Health & Fitness', 'Workouts', 'Fitness Challenges & Workouts'),
(83, 'Music', 'Music Production', 'Electronic Music Production'),
(84, 'Food & Cooking', 'Recipes', 'Nutrition & Healthy Recipes'),
(85, 'Music', 'Instruments', 'Guitar Gear & Equipment Reviews'),
(86, 'News & Politics', 'Political Analysis', 'Political Commentary & Analysis'),
(87, 'Outdoors', 'Winter Activities', 'Winter Camping & Cold Weather Gear'),
(88, 'Arts & Media', 'Photography Projects', 'Creative Photography Projects'),
(89, 'Music', 'Music Production', 'Music Recording & Studio Setup'),
(90, 'Technology', 'Other', 'Technology Tutorials & How-To'),
(91, 'Music', 'Instruments', 'Musical Instrument Reviews'),
(92, 'News & Politics', 'World News', 'International News & Global Affairs'),
(93, 'Gaming', 'Gameplay', 'Gaming News & Industry Updates'),
(94, 'Music', 'Music Gear', 'Professional Music Equipment'),
(95, 'Entertainment', 'Comedy', 'Comedy Sketches & Entertainment'),
(96, 'Hobbies', 'LEGO Technic', 'LEGO Technic & Advanced Builds'),
(97, 'Technology', '3D Printing', '3D Printing Technology & Reviews'),
(98, 'Sports', 'Sports History', 'Sports History & Analysis'),
(99, 'Gaming', 'Gameplay', 'Gaming Commentary & Let''s Plays'),
(100, 'Education', 'Academic Subjects', 'Scientific Demonstrations & Education'),
(101, 'Business', 'Other', 'Restaurant Business & Food Industry'),
(102, 'Finance', 'Trading', 'Stock Trading Strategies & Tips'),
(103, 'Finance', 'Market Analysis', 'Real Estate Market Analysis'),
(104, 'DIY & Crafts', 'Home DIY', 'DIY Home Projects & Repairs'),
(105, 'Travel', 'Destination Guides', 'Travel Tips & Destination Reviews'),
(106, 'Finance', 'Personal Finance', 'Personal Finance & Money Management'),
(107, 'Outdoors', 'Equipment', 'Outdoor Gear & Equipment Reviews'),
(108, 'Hobbies', 'Card Games', 'Trading Card Games & Collectibles'),
(109, 'Gaming', 'Gameplay', 'Gaming Challenges & Competitions'),
(110, 'Arts & Media', 'Drawing', 'Drawing Tutorials & Techniques'),
(111, 'Gaming', 'Gameplay', 'Esports & Competitive Gaming'),
(112, 'Technology', 'Electronics', 'Robotics Projects & Engineering'),
(113, 'Automotive', 'Car Repair', 'Auto Repair & Car Maintenance'),
(114, 'Technology', 'Photography & Video', 'Photography Accessories & Gear'),
(115, 'Home & Garden', 'Wall Repair', 'Drywall & Ceiling Repairs'),
(116, 'DIY & Crafts', 'Crafts', 'Epoxy Resin Art & Tables'),
(117, 'Lifestyle', 'Home & Organization', 'Extreme Decluttering & Minimalism'),
(118, 'DIY & Crafts', 'Sewing & Textiles', 'Sewing Projects & Fashion DIY'),
(119, 'Entertainment', 'Star Wars Lore', 'Star Wars Lore & Deep Dives'),
(120, 'Education', 'Skills Training', 'Educational Series & Crash Courses'),
(121, 'Lifestyle', 'Other', 'Micro Living & Tiny Apartments'),
(122, 'Technology', 'Tech Industry', 'Tech News & Industry Updates'),
(123, 'Business', 'Business Strategy', 'Business Strategy & Management'),
(124, 'DIY & Crafts', 'Woodworking', 'Epoxy River Tables & Furniture'),
(125, 'Lifestyle', 'Alternative Living', 'Van Life & Nomadic Living'),
(126, 'Lifestyle', 'Fashion & Beauty', 'Simple Living & Lifestyle Design'),
(127, 'Finance', 'Housing Market', 'Housing Market Trends & Analysis'),
(128, 'Business', 'Other', 'Real Estate Agent Training & Tips'),
(129, 'Business', 'Other', 'Public Speaking & Communication'),
(130, 'Entertainment', 'Creator Content', 'YouTube Milestones & Celebrations'),
(131, 'Health & Wellness', 'Eye Care', 'Eye Health & Vision Care'),
(132, 'Technology', 'Electronics', 'Electronics Projects & Arduino'),
(133, 'Education', 'Academic Subjects', 'Chemistry & Science Experiments'),
(134, 'Hobbies', 'Pokemon Cards', 'Pokemon Card Collecting & Opening'),
(135, 'Gaming', 'Gameplay', 'Fortnite Gameplay & Strategies'),
(136, 'Lifestyle', 'Family Life', 'Mom Life & Family Organization'),
(137, 'Outdoors', 'Winter Sports', 'Winter Outdoor Adventures'),
(138, 'DIY & Crafts', 'Other', 'RV Renovations & Upgrades'),
(139, 'Arts & Media', 'Art History', 'Art History & Technique Analysis'),
(140, 'Arts & Media', 'Painting Tutorials', 'Step-by-Step Painting Tutorials'),
(141, 'Hobbies', 'LEGO Collecting', 'LEGO Star Wars Collections'),
(142, 'Sports', 'Formula 1', 'Formula 1 Racing & Analysis'),
(143, 'Technology', 'Photography & Video', 'Action Camera Reviews & Tests'),
(144, 'Health & Fitness', 'Other', 'Bodybuilding & Muscle Growth'),
(145, 'Business', 'Other', 'Passive Income & Side Hustles'),
(146, 'Sports', 'Martial Arts', 'Martial Arts Training & Techniques'),
(147, 'Education', 'Educational Content', 'Medical Education & Health Facts'),
(148, 'Entertainment', 'Slow Motion', 'Slow Motion Science & Experiments'),
(149, 'Hobbies', 'Cosplay', 'Prop Making & 3D Printed Cosplay'),
(150, 'Sports', 'College Football', 'College Football Coverage & Analysis'),
(151, 'Home & Garden', 'Bathroom Design', 'Bathroom Design & Renovation Ideas'),
(152, 'Music', 'Other', 'Music Reaction Videos & Commentary'),
(153, 'DIY & Crafts', 'Woodworking', 'Handmade Cutting Boards & Crafts'),
(154, 'Technology', 'Mobile & Computing', 'iOS Tips & Apple Ecosystem'),
(155, 'Technology', 'Electronics', 'Electronics Assembly & Soldering'),
(156, 'Home & Garden', 'Kitchen Storage', 'Kitchen Organization & Storage Hacks'),
(157, 'Entertainment', 'Live Interaction', 'Live Q&A Sessions & Community'),
(158, 'Business', 'E-commerce', 'Amazon Business & E-commerce Tips'),
(159, 'Technology', 'Electronics', 'Advanced Electronics & Circuit Design'),
(160, 'Lifestyle', 'Home & Organization', 'Deep Cleaning & Organization Methods'),
(161, 'Arts & Media', 'Videography', 'Professional Videography & Filming'),
(162, 'Lifestyle', 'Other', 'Spiritual Growth & Faith Journey'),
(163, 'Gaming', 'Gameplay', 'Gaming Tutorials & Walkthroughs'),
(164, 'Lifestyle', 'Other', 'Alternative Housing & Off-Grid Living'),
(165, 'Technology', 'Programming', 'Python Programming & Data Science'),
(166, 'Home & Garden', 'Custom Storage', 'Custom Storage Solutions & Built-ins'),
(167, 'DIY & Crafts', 'Metalworking', 'Professional Knife Making & Bladesmithing'),
(168, 'Business', 'Entrepreneurship', 'Business Growth & Scaling Strategies'),
(169, 'Arts & Media', 'Digital Art', 'Digital Art & Illustration Techniques'),
(170, 'DIY & Crafts', 'Metalworking', 'Advanced Metalworking & Fabrication'),
(171, 'Education', 'Educational Content', 'Coding Bootcamps & Tech Education'),
(172, 'Education', 'Language Learning', 'Language Learning Tips & Resources'),
(173, 'DIY & Crafts', 'Woodworking', 'Precision Woodworking & Joinery'),
(174, 'Finance', 'Wealth Building', 'Investment Strategies & Wealth Building'),
(175, 'Technology', 'Programming', 'Web Development & JavaScript'),
(176, 'DIY & Crafts', 'Workshop', 'Workshop Organization & Tool Storage'),
(177, 'Arts & Media', 'Documentary', 'Documentary Filmmaking & Storytelling'),
(178, 'DIY & Crafts', 'Woodworking', 'Unique Furniture Designs & Builds'),
(179, 'DIY & Crafts', 'Workshop', 'Professional Tool Reviews & Comparisons'),
(180, 'Home & Garden', 'Space Saving', 'Space-Saving Furniture & Solutions'),
(181, 'Lifestyle', 'Fashion & Beauty', 'Lifestyle Transformation & Habits'),
(182, 'Home & Garden', 'Modular Storage', 'Modular Storage Systems & Organization'),
(183, 'Technology', 'Programming', 'Full-Stack Development & Coding'),
(184, 'Music', 'Music Business', 'Professional Music Industry Insights'),
(185, 'DIY & Crafts', 'Woodworking', 'Advanced Woodworking Techniques'),
(186, 'Education', 'Educational Content', 'Effective Study Methods & Learning'),
(187, 'Arts & Media', 'Mixed Media', 'Mixed Media Art & Experimental Techniques'),
(188, 'Music', 'Music Business', 'Music Business & Industry Tips'),
(189, 'Home & Garden', 'Creative Storage', 'Creative Storage & Organization Ideas'),
(190, 'Arts & Media', 'Traditional Art', 'Traditional Art Techniques & Methods'),
(191, 'DIY & Crafts', 'Workshop', 'Specialty Tool Making & Jigs'),
(192, 'Travel', 'Cultural Travel', 'Global Travel & Cultural Experiences'),
(193, 'Business', 'E-commerce', 'E-commerce Strategies & Online Sales'),
(194, 'Music', 'Other', 'Professional Audio Production Tips'),
(195, 'Lifestyle', 'Other', 'Life Philosophy & Deep Thoughts'),
(196, 'DIY & Crafts', 'Workshop', 'Custom Jigs & Workshop Solutions'),
(197, 'DIY & Crafts', 'Crafts', 'Artisan Crafts & Handmade Goods'),
(198, 'Lifestyle', 'Alternative Living', 'Mobile Home & Tiny House Tours'),
(199, 'Travel', 'Adventure Travel', 'Adventure Planning & Travel Prep'),
(200, 'Education', 'Educational Content', 'Cultural Education & World Awareness'),
(201, 'Business', 'Digital Marketing', 'Photography Business & Marketing'),
(202, 'Technology', 'AI & Innovation', 'Future Tech & Innovation Trends'),
(203, 'Education', 'Educational Content', 'Art Education & Teaching Methods'),
(204, 'DIY & Crafts', 'Other', 'Tiny House Building & Design'),
(205, 'Lifestyle', 'Fashion & Beauty', 'Lifestyle Optimization & Efficiency'),
(206, 'Home & Garden', 'Custom Shelving', 'Custom Shelving & Display Solutions'),
(207, 'Outdoors', 'Extreme Camping', 'Extreme Weather Camping & Gear'),
(208, 'Education', 'Language Learning', 'Polyglot Tips & Multiple Languages'),
(209, 'Music', 'Music Theory', 'Music Theory & Composition'),
(210, 'DIY & Crafts', 'Workshop', 'Home Workshop Setup & Organization'),
(211, 'Music', 'Performance', 'Live Music & Concert Coverage'),
(212, 'Business', 'Other', 'Content Strategy & Channel Growth'),
(213, 'Education', 'Educational Content', 'Scientific Art & STEAM Projects'),
(214, 'DIY & Crafts', 'Workshop', 'Professional Workshop Equipment'),
(215, 'Education', 'Educational Content', 'Global Perspectives & World Views');

-- Update all videos in a single query
UPDATE videos v
SET 
  topic_domain = COALESCE(m.new_domain, v.topic_domain),
  topic_niche = COALESCE(m.new_niche, v.topic_niche),
  topic_micro = COALESCE(m.new_micro, v.topic_micro)
FROM topic_hierarchy_mapping m
WHERE v.topic_cluster_id = m.cluster_id
  AND v.bertopic_version = 'v1_2025-08-01';

-- Handle outliers
UPDATE videos
SET 
  topic_domain = 'Outlier',
  topic_niche = 'Outlier',
  topic_micro = 'Outlier'
WHERE topic_cluster_id = -1
  AND bertopic_version = 'v1_2025-08-01';

-- Drop temporary table
DROP TABLE topic_hierarchy_mapping;

-- Show update counts
SELECT 
  topic_domain,
  topic_niche,
  COUNT(*) as video_count
FROM videos
WHERE bertopic_version = 'v1_2025-08-01'
GROUP BY topic_domain, topic_niche
ORDER BY topic_domain, topic_niche;